name: Submit Curvenote
description: Submit a project to a Curvenote site or journal
author: Curvenote Inc.
branding:
  icon: package
  color: blue
inputs:
  working-directory:
    description: Install typst for PDF rendering
    required: true
  CURVENOTE_TOKEN:
    description: Curvenote token for authentication
    required: true
  venue:
    description: 'The site or venue that this project is being submitted to'
    required: true
  kind:
    description: 'The kind of the submission'
    required: true
  draft:
    description: 'Flag to indicate if the submission should be a draft'
    default: 'false'
runs:
  using: composite
  steps:
    - name: Submit project to Curvenote
      working-directory: ${{ inputs.working-directory }}
      env:
        CURVENOTE_TOKEN: ${{ inputs.CURVENOTE_TOKEN }}
      shell: bash
      run: |
        if [ "${{ inputs.draft }}" = "true" ]; then
          curvenote submit ${{ inputs.venue }} --kind ${{ inputs.kind }} --draft -y
        else
          curvenote submit ${{ inputs.venue }} --kind ${{ inputs.kind }} -y
        fi
