name: Curvenote Preview or Submit
description: Preview or submit a project to a Curvenote site
author: Curvenote Inc.
branding:
  icon: package
  color: blue
inputs:
  id:
    description: |
      The ID of the submission, used to store the logs on github

      This should match the submission id in the myst.yml project config
    required: true
  working-directory:
    description: Root directory of project with myst.yml
    required: true
  venue:
    description: The site or venue that this project is being submitted to
    required: true
  collection:
    description: The venue's collection that this project is being submitted to
  kind:
    description: The kind of the submission
    required: true
  draft:
    description: Flag to indicate if the submission should be a draft
    default: false
runs:
  using: composite
  steps:
    - name: Submit project to Curvenote
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        if [ "${{ inputs.draft }}" = "true" ]; then
          DRAFT="--draft"
        fi
        if [ -n "${{ inputs.collection }}" ]; then
          COLLECTION="--collection ${{ inputs.collection }}"
        fi
        curvenote submit ${{ inputs.venue }} --kind "${{ inputs.kind }}" $COLLECTION $DRAFT -y
    - name: Upload Curvenote Logs
      uses: actions/upload-artifact@v4
      with:
        name: submit-${{ inputs.id }}
        path: ${{ inputs.working-directory }}/_build/logs
