name: Comment based on build results
description: Add a comment to the PR or commit
author: Curvenote Inc.
branding:
  icon: package
  color: blue
inputs:
  title:
    description: The title of the comment, put in bold at the top and ensures that the correct comment is updated
    default: Curvenote Preview
  comment:
    description: The body of the comment, in markdown
    required: true
runs:
  using: composite
  steps:
    - name: Find PR Comment
      if: ${{ github.event.pull_request.number }}
      uses: peter-evans/find-comment@60c57613a233a2143853d3f68874167868b5d040
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ inputs.title }}
    - name: Create PR comment
      if: ${{ github.event.pull_request.number && steps.fc.outputs.comment-id == '' }}
      uses: peter-evans/create-or-update-comment@dec9d02d7ba794da3485751abf67551b0724c66b
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          **${{ inputs.title }}**

          ${{ inputs.comment }}
    - name: Update PR comment
      if: ${{ github.event.pull_request.number && steps.fc.outputs.comment-id != '' }}
      uses: peter-evans/create-or-update-comment@dec9d02d7ba794da3485751abf67551b0724c66b
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
        body: |
          **${{ inputs.title }}**

          ${{ inputs.comment }}
    - name: Create Commit comment
      if: ${{ !github.event.pull_request.number }}
      uses: peter-evans/commit-comment@1d732d08f4ceed8b5960ae40d4206620a3b8d38f
      with:
        body: |
          **${{ inputs.title }}**

          ${{ inputs.comment }}
