name: Comment based on build results
description: Add a comment to the PR
author: Curvenote Inc.
branding:
  icon: package
  color: blue
inputs:
  title:
    description: The title of the comment, put in bold at the top and ensures that the correct comment is updated
    default: Curvenote Preview
  comment:
    description: The body of the comment, in markdown
    required: true
runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: ${{ inputs.title }}
    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          **${{ inputs.title }}**

          ${{ inputs.comment }}
    - name: Update comment
      if: steps.fc.outputs.comment-id != ''
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
        body: |
          **${{ inputs.title }}**

          ${{ inputs.comment }}
