name: Curvenote - Submission Summary
description: A GitHub action to give a summary of the submission jobs that were run
author: Curvenote Inc.
branding:
  icon: package
  color: blue
inputs:
  matrix: The build matrix created in the strategy step (JSON)
runs:
  using: 'node20'
  main: 'dist/index.js'
outputs:
  comment:
    description: A body of a comment to notify
