name: Curvenote - Deployment Strategy
description: A GitHub action to choose how to check, preview and publish articles
author: Curvenote Inc.
branding:
  icon: package
  color: blue
inputs:
  changed-files:
    description: |
      A comma-separated list of changed files.

      We recommend using https://github.com/tj-actions/changed-files
    required: true
  monorepo:
    description: |
      Indicate that this repository contains multiple projects that should be published.

      For example, if you have multiple articles, or tutorials that should be previewed
      and submitted when there are changes in the repository.
    required: false
    default: false
  path:
    description: |
      The root directory path(s) where the Curvenote CLI will be invoked.
      If `multiple` paths are being used, separate the `path` string with ','.
      The paths can also be glob-like patterns (but only one `*`), for example:

      ```yaml
      path: my/project
      path: my/paper, my/poster
      path: papers/*, posters/*
      ```

      The default path is the root of the repository.
    required: false
    default: '.'
  id-pattern-regex:
    description: |
      A regular expression that all IDs must follow, by default this matches a UUID.

      This can be used to enforce that all project IDs follow a specific pattern, such as,
      the conference name + year.

      The ID must also satisfy alphanumeric characters, dashes, and underscores.
    type: string
    default: '^([a-zA-Z0-9-]{36})$'
  enforce-single-folder:
    description: |
      When true, an error will be raised if a pull-request is touching multiple
      different folders. This can either be `true` or a label string.
      Multiple labels can be added with comma-separated values.

      If labels are used to control this property, the pull request will only fail in
      PRs with these labels.

      This can be used in conjunction with the `preview-label`, for example, if they
      are both `paper` then the PRs with those labels will be required to only make changes
      in a single folder and will not be previewed if that condition fails.
      However, you can add additional preview labels, e.g. `all-papers`, which will build
      previews for all papers, as the single folder condition is not enforced for that label.
    required: false
    default: false
  preview-label:
    description: |
      A pull-request label that indicates the preview and checks should be run.
      Multiple labels can be added with comma-separated values.

      If no label is supplied, the preview will run on all PRs.
    required: false
  submit-label:
    description: |
      A pull-request label that indicates the branch should be turned into a submission.
      This will notify all curators of the Curvenote site.

      The submission identifiers will be written directly to the repository in a commit,
      and the submission will be available to be merged on the Curvenote platform.

      A submission will not happen unless both the `enforce-single-folder` and `preview-label`
      conditions are satisfied.
    required: false
    default: ready
runs:
  using: 'node20'
  main: 'dist/index.js'
outputs:
  check:
    description: A boolean value to indicate whether a check job should occur
  preview:
    description: A boolean value to indicate whether a preview job should occur
  matrix:
    description: >
      A JSON object describing the build matrix, this can be used to inform other build steps.

      Each step will include:

      - `id`: The local identifier for the submission job (only used between github actions)
      - `working-directory`: The directory that the step should complete in
      - `draft`: True if submission should be made as a draft
