name: Setup Curvenote
description: Setup the Curvenote CLI
author: Curvenote Inc.
branding:
  icon: package
  color: blue
inputs:
  typst:
    description: Install typst for PDF rendering
    default: 'true'
  images:
    description: Install image transformation tools
    default: 'true'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install Curvenote
      run: npm install -g curvenote
      shell: bash
    - name: Install Typst for PDF builds
      if: ${{ inputs.typst == 'true' }}
      uses: typst-community/setup-typst@v3
    - name: Install image transformation utilities
      if: ${{ inputs.images == 'true' }}
      shell: bash
      run: |
        sudo apt-get install -y inkscape imagemagick webp ghostscript
        sudo sed -i '/domain="coder" rights="none"/d' /etc/ImageMagick-6/policy.xml
