name: PR Test Release
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout temporary branch
        run: |
          git checkout -b release/PR${{ github.event.number }}
      - name: Bump version
        run: |
          sed -i s/@main/@PR${{ github.event.number }}/g .github/workflows/publish.yml
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "🧪 PR${{ github.event.number }}"
      - name: Tag version
        run: |
          git tag PR${{ github.event.number }} --force
      - name: Push tags
        run: |
          git push origin --tags --force
      - name: Comment on PR
        uses: curvenote/actions/upsert-comment@v1
        with:
          comment: 'Test this pull request: curvenote/actions/.github/workflows/publish.yml@PR${{ github.event.number }}'
