name: PR Test Release
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
jobs:
  release:
    name: Create PR Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fine-grained PAT with contents:write and workflows:write scopes
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Checkout temporary branch
        run: |
          git checkout -b release/PR${{ github.event.number }}
      - name: Stamp version into workflows
        run: |
          sed -i s/@main/@PR${{ github.event.number }}/g .github/workflows/publish.yml
          sed -i s/@main/@PR${{ github.event.number }}/g .github/workflows/draft.yml
          sed -i s/@main/@PR${{ github.event.number }}/g .github/workflows/submit.yml
      - name: Build dist content
        run: |
          npm install
          npm run build
      - name: Commit changes
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add .github/workflows/publish.yml
          git add .github/workflows/draft.yml
          git add .github/workflows/submit.yml
          git add -f strategy/dist
          git add -f submit-summary/dist
          git commit -m "🧪 PR${{ github.event.number }}"
      - name: Tag version
        run: |
          git tag PR${{ github.event.number }} --force
      - name: Push tags
        run: |
          git push origin --tags --force
      - name: Comment on PR
        uses: curvenote/actions/upsert-comment@v1
        with:
          comment: |
            You may test this pull request by updating your action:

            ```yaml
            ...
            jobs:
              publish:
                uses: curvenote/actions/.github/workflows/publish.yml@PR${{ github.event.number }}
              with:
                ...
            ```
