name: push
on:
  workflow_call:
    inputs:
      landing-content:
        description: Optional landing content for site initialization
        required: false
        type: string
      debug:
        description: Run curvenote commands in debug mode for verbose log messages
        required: false
        default: 'false'
        type: string
    secrets:
      CURVENOTE:
        description: Curvenote API token (usually `secrets.CURVENOTE_TOKEN`)
        required: true
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: curvenote/actions/setup@main
      - name: Run Curvenote Push (private)
        if: ${{ inputs.landing-content == '' }}
        shell: bash
        env:
          CURVENOTE_TOKEN: ${{ secrets.CURVENOTE }}
        run: |
          if [ "${{ inputs.debug }}" = "true" ]; then
            DEBUG="-d"
          fi
          curvenote work push $DEBUG -y
      - name: Run Curvenote Push (public)
        if: ${{ inputs.landing-content != '' }}
        shell: bash
        env:
          CURVENOTE_TOKEN: ${{ secrets.CURVENOTE }}
        run: |
          if [ "${{ inputs.debug }}" = "true" ]; then
            DEBUG="-d"
          fi
          curvenote work push $DEBUG --public -y
      - name: Set Site Landing Content
        if: ${{ inputs.landing-content != '' }}
        shell: bash
        env:
          CURVENOTE_TOKEN: ${{ secrets.CURVENOTE }}
        run: |
          if [ "${{ inputs.debug }}" = "true" ]; then
            DEBUG="-d"
          fi
          curvenote site init ${{ inputs.landing-content }} $DEBUG --set-content
