name: PR Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine new version
        # run:
      - name: Checkout branch
        run: |
          git checkout -b release/v1.0.0
      - name: Bump version
      - name: Tag version
        run: |
          git tag v1 --force
          git tag v1.0 --force
          git tag v1.0.0
      - name: Push tags
        run: |
          git push origin --tags --force

# on pull request to main
# pull code
# check out new branch
# patch main > PR#
# tag as PR#
# force push tags

# on merge to main
# pull code
# edit readme to v0?
# check out new branch
# patch main > v0.0.0
# tag as v0, v0.0, v0.0.0
# force push tags

